### ISSUE TITLE
Errors trying to install/configure

### ISSUE THREAD

**Issue by jawaidbazyar** [urueedi/kazoo-provision#1]
Hi, I'm trying to install, but I get these errors.

The brand_provisioner database is created, but apparently it can't copy the files.

Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fmitel%252F67xx%252F6753
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fcisco%252Fspa3xx%252F501g
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fcisco%252Fspa3xx%252F303g
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252F3xx%252F320-2
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fmitel%252F67xx%252F6753-1
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fmitel%252F67xx%252F6730
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252F8xx%252F820
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252F3xx%252F320
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fmitel%252F67xx%252F6753-2
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fpanasonic%252Fkx%252Fuds124
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252Fm9x%252Fm9
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fmitel%252F67xx%252F6731
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252F8xx%252F821
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252F3xx%252F320-1
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252F3xx%252F370
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252Fm9x%252Fm9r
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:phonetree
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252Fm3x%252Fm3
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252F3xx%252F360
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fpanasonic%252Fkx%252Ftgp500
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:_design%252Fprovisioner
Sag Error: put() needs an object for data - are you trying to use delete()?DB:brand_provisioner file:ui%252Fsnom%252F3xx%252F300
CouchDB Error: file_exists (The database could not be created, the file already exists.)DB:system_config
Sag Error: put() needs an object for data - are you trying to use delete()?DB:system_config file:crossbar.devices

**Comment by jawaidbazyar** [comment]
changing the json_decode like in restore() this this, fixed this: looks like you changed your directory structure but not the restore function.

```
        $obj = json_decode(file_get_contents($dir.$entry."/".$entry.".json"));
```

**Comment by urueedi** [comment]
thanks, i have update with our suggestions!
