### ISSUE TITLE
Blank webpage on adding provisioner URL to config.js

### ISSUE THREAD

**Issue by sangramrath** [urueedi/kazoo-provision#10]
Kazoo version 3.22-18

1 - Installed kazoo from 2600hz repository
2 - Replaced devices.json and user.json from DEVELOP to application/crossbar/priv/couchdb/accounts/ (it was not in application/crossbar/priv/devices.json as mentioned in instructions. There was also a folder called schema where there was devices.json and user.json)
3 - Rebuilt crossbar (only) and restarted crossbar. Restarted whistle_apps and flushed cache too
4 - git clone monster-ui from your repo
5 - git clone kazoo-provision from your repo
6 - Ran ./setup.php and pressed Y to install brand_provisioner to couchdb. I also get the error "Sag Error: cURL error #56: Failure when receiving data from the peerDB:system_config"

7 - I modify the config.js to add provisioner URL and load webpage, the webpage is blank. If I remove provisioner URL, the page loads.

**Comment by urueedi** [comment]
Install the needed php-cli ++ descript in README

**Comment by sangramrath** [comment]
Thanks for the quick response, I already have that installed. Plus other pre-requisites as per Readme. AllowOverride is also set to All for "/".

**Comment by sangramrath** [comment]
In your instructions point 1:
**INSTALL kazoo-platform (from this repository because of changes: use 3.22) If not install kazoo-urueedi, change files application/crossbar/priv/devices.json and users.json from this DEVELEOP directory and recompile and restart crossbar and (sup whapps_maintenance migrate) to renew couchdb!**
Do we install kazoo from 2600hz repo or from your repo, did not find a kazoo-platform or kazoo-urueedi repo under your account.

**Comment by urueedi** [comment]
it runs wih 3.22-18 and later 3.22 in Centos or Debain

**Comment by sangramrath** [comment]
Okay, but is it ok if its installed directly from kazoo's repo? I have 3.22-18.

**Comment by sangramrath** [comment]
@urueedi I got the blank page issue resolved. Thank you, the config.js was missing a simple ','. 
I now have a different issue where accounts, callflow are blank. I have an error stating "A wild Javascript error appears..."
Appreciate your assistance.
![wildjavascript-error](https://cloud.githubusercontent.com/assets/6134395/25095920/61ee8292-23bb-11e7-8658-a02d03c4990b.PNG)

**Comment by urueedi** [comment]
Wath is loaded, URL of this error?
You will find more info on Error console of your Browser!

**Comment by sangramrath** [comment]
Happens with http://<domain>/monster-ui/#/apps/callflows and all apps such as accounts, number manager.

**Comment by urueedi** [comment]
Maybe you have installed wrong versions? i think you need payed support.

**Comment by sangramrath** [comment]
How much is the paid support?

**Comment by urueedi** [comment]
please ask that on https://www.opennet.ch/page/website.contactus

**Comment by sangramrath** [comment]
Thanks, done.
