### ISSUE TITLE
Unsure how to do step 8

### ISSUE THREAD

**Issue by jawaidbazyar** [urueedi/kazoo-provision#2]
Step 8 in the instructions says (below). However, I cannot figure out where to enable "Automatic Devicesettings".

Go to your account settings and enable (Automatic Devicesettings) in monster-ui
URL-Password => [your_pass] is used in GET-string of phone snom now only
Domainrestriction => [customer_home_domain] e.g. customer.domain.com (dyndns) only this domain will be able to consume provision if putin
Phone Admin Password => [your_pass] access password to local phone
Zoiper Token => [zoipertoken] This is used for autoprovision with smartphone with zoiper
Automatic Devicesetting => enable to allow this autoprovision features on this account for all his phones
User devicesetting => enable to allow devicesettings in the userportal

**Comment by urueedi** [comment]
The "Automatic Devicesettings" is in monster-ui at account from this repository

**Comment by ynasida** [comment]
"Install monster-ui (from this repository because of adds in ui) and fping, php-cli, php, php-xml"

I think that link "for this repository" is missed.  Can you please provide new link that i can use to get monster-ui files with changes you did ?

Thanks
