### ISSUE TITLE
centos: apache config problems "Folder phones doesnt exist"

### ISSUE THREAD

**Issue by canito2004** [urueedi/kazoo-provision#3]
Hi, I am trying to have this provisioner working on Kazoo-UI, however, I dont have much clues about the procedure.   Can you please post a simple guide on how to make kazoo-provision to work on old Kazoo-UI.   

What I have done so far is to git clone this into /var/www/html  (my webroot), then followed steps explained here.   On Kazoo-ui i added something like:   provisioner: 'http:/My-IP/provisioner/',   

Restarted all services, but not results.

**Comment by canito2004** [comment]
Hi, 
  I finally got somehow this working on Monster-ui,  however, when I click on Add new SIP Device, I got nothing.   By checking the logs in the webserver: 

 File does not exist: /var/www/html/provisioner/phones  
"GET /provisioner/phones?_=1455688988359 HTTP/1.1" 404 296

"phones" is not part of the folders in this repo.    is there something missing?   Can you please give me some clues?.

**Comment by urueedi** [comment]
Hi 
Where and what have you installed the autoprovisioner?
In this directory? /var/www/html/
and with name of provisioner?

"phones" will redirected by mod_rewrite of apache

**Comment by canito2004** [comment]
Hi,  
  Thanks for your prompt reply, please find below more detail of my installation:  

On /var/www/html I have:  

4 -rw-r--r-- 1 root root  230 Feb 15 12:03 index.html
4 drwxr-xr-x 7 root root 4096 Feb 17 17:08 monster-ui   << urueedi version
4 drwxr-xr-x 7 root root 4096 Feb 17 17:31 provisioner

monster-ui + apps are the modified version posted in your repositories. 

Inside provisioner  I downloaded the files of this git (kazoo-provision): 

 4 -rw-r--r--  1 root root   251 Feb 17 15:24 changes.txt
 4 -rw-r--r--  1 root root  1726 Feb 17 15:24 config.php
 4 drwxr-xr-x  4 root root  4096 Feb 17 15:24 DB_INSTALL
 4 drwxr-xr-x  2 root root  4096 Feb 17 15:24 DEVELOP
12 -rw-r--r--  1 root root 11670 Feb 17 15:24 functions_mitel.php
44 -rw-r--r--  1 root root 42581 Feb 17 15:24 functions.php
28 -rw-r--r--  1 root root 24655 Feb 17 15:24 functions_snom.php
16 -rw-r--r--  1 root root 14786 Feb 17 15:24 functions_yealink.php
 4 -rw-r--r--  1 root root   529 Feb 17 15:24 functions_zoiper.php
 0 -rw-r--r--  1 root root     0 Feb 17 15:24 index.html
16 -rw-r--r--  1 root root 15922 Feb 17 15:24 LICENSE
 4 drwxr-xr-x  2 root root  4096 Feb 17 15:24 m3
 4 drwxr-xr-x  3 root root  4096 Feb 17 15:24 phplib
 4 drwxr-xr-x 12 root root  4096 Feb 17 15:24 prov
 8 -rw-r--r--  1 root root  6667 Feb 17 15:24 README.md
 4 -rw-r--r--  1 root root  1334 Feb 17 15:35 settings.php
 4 -rwxr-xr-x  1 root root   765 Feb 17 15:24 setup.php

on /var/www/html/provisioner  there is not .htaccess file. 

---  on httpd error_log:  

[Thu Feb 18 08:27:49 2016] [error] [client my-network-ip.185] File does not exist: /var/www/html/monster-ui/undefined, referer: http://my-network-ip.18/monster-ui/
[Thu Feb 18 08:29:10 2016] [error] [client my-network-ip.185] File does not exist: /var/www/html/provisioner/phones, referer: http://my-network-ip.18/monster-ui/

---------------------- some screenshots ----- 

![nimbus-image-1455744451069](https://cloud.githubusercontent.com/assets/17263822/13125537/2bebd482-d61a-11e5-9b77-145263b600b0.png)
![nimbus-image-1455744532781](https://cloud.githubusercontent.com/assets/17263822/13125536/2beb39c8-d61a-11e5-8cdd-2712f7260ac3.png)
![nimbus-image-1455744588668](https://cloud.githubusercontent.com/assets/17263822/13125538/2befe3b0-d61a-11e5-8e42-e3064af52bda.png)

**Comment by urueedi** [comment]
Thank you for details
copy in /var/www/html/ folder:

4 -rw-r--r-- 1 root root 230 Feb 15 12:03 index.html
4 drwxr-xr-x 7 root root 4096 Feb 17 17:08 monster-ui << urueedi version
4 drwxr-xr-x 7 root root 4096 Feb 17 17:31 provisioner << (also .htaccess must be in directory)

Can you access the monster-ui like: http://yourIP/monster-ui  => OK?
Then you have to set in monster-ui/js/config.js provisioner_url = 'http://yourIP/provisioner'
Now you can test by: http://yourIP/provisioner/phone => sould see all phone in json-format
To disable the ssl-cert popup set in config.js -> selfcerthttps: false,

**Comment by canito2004** [comment]
Can you access the monster-ui like: http://yourIP/monster-ui => OK?   RESP:  This is working fine. 

Then you have to set in monster-ui/js/config.js provisioner_url = 'http://yourIP/provisioner'  RESP: Done, I set provisioner_url variable and now Add new SIP Device screen pop up.  

Now you can test by: http://yourIP/provisioner/phone => sould see all phone in json-format  RESP:  There seems my rewrite module is not working.    RESP:  Still not working, there seems some issue with apache: 

[Thu Feb 18 09:06:21 2016] [error] [client my-ip-.185] PHP Notice:  Undefined index: Access-Control-Request-Headers in /var/www/html/provisioner/settings.php on line 14
[Thu Feb 18 09:06:27 2016] [error] [client my-ip.185] File does not exist: /var/www/html/provisioner/phones

To disable the ssl-cert popup set in config.js -> selfcerthttps: false,  RESP:  Done. This is not pop up anymore.

**Comment by urueedi** [comment]
Found it change in /etc/httpd/conf/httpd.conf
<     Options FollowSymLinks

> ```
> Options Indexes FollowSymLinks
> ```

<     AllowOverride All

> ```
> AllowOverride None
> ```

**Comment by canito2004** [comment]
Solve it.  This is awkward, I just found AllowOverride was on None in Apache.

**Comment by canito2004** [comment]
Will this UI allow me to enter the MAC address and model of the phone?

**Comment by urueedi** [comment]
Choose your model putin this macadress and it give you a provstring to put in the phone, reboot phone, proved

for the provstring is used from js/config.js provisioner: / provisioner_http:

**Comment by canito2004** [comment]
The screen doesn't display the option to select Model or set MAC Address  

![nimbus-image-1455753998175](https://cloud.githubusercontent.com/assets/17263822/13129244/bd2560f2-d62f-11e5-996c-bd70046fb6ce.png)

**Comment by urueedi** [comment]
You need to add a new sip-device first and to choose a model, change of models is not supported on this version
