### ISSUE TITLE
Blank page when accessing the prov url

### ISSUE THREAD

**Issue by pramsky** [urueedi/kazoo-provision#4]
I am getting a blank page when accessing the prov url created for a yealink test phone. I don't see any php errors in the logs. 

Any suggestions as to what I might have missed ?

**Comment by urueedi** [comment]
Thats normal, to see you have to use like this: URL/provisioner/prov/yealink/001577885533.cfg?mac=001577885533&qpass={urlpass}&model=yealinksip-t41g&firmware=Yealink SIP-T48G 35.80.0.70 00:15:77:88:33:55
