### ISSUE TITLE
(null): can't create socket (must run as root?) : Permission denied

### ISSUE THREAD

**Issue by smrdoshi** [urueedi/kazoo-provision#7]
We are trying to integrate monster UI and kazoo provision source code as per the documentation steps but somehow we are getting below errors in apache log, 

null): can't create socket (must run as root?) : Permission denied
(null): can't create socket (must run as root?) : Permission denied
(null): can't create socket (must run as root?) : Permission denied
(null): can't create socket (must run as root?) : Permission denied
(null): can't create socket (must run as root?) : Permission denied
[Fri Mar 03 14:25:29 2017] [error] [client 59.88.125.217] PHP Notice:  Undefined index: Access-Control-Request-Headers in /var/www/html/kazoo-provision/settings.php on line 14, referer: http://14.131.13.24/monster-ui/
(null): can't create socket (must run as root?) : Permission denied
(null): can't create socket (must run as root?) : Permission denied

We tried to debug php class files but somehow unable to reach to solution.
Please help!!

**Comment by urueedi** [comment]
This look like a apache problem, try to sudo fping or remove it from source

**Comment by smrdoshi** [comment]
Do you want me to comment below code? 

if($testhost) {
        $fping = exec("fping $testhost -t 50");
        if($fping == $testhost.' is alive') {
            $ret = json_decode(check_http('http://'.$testhost.':'.$dbport, 2),TRUE);
            show_debug("Check couchdb:".$testhost.":".$dbport."/",'d', __FILE__ ,__FUNCTION__, __LINE__);
            if($ret['couchdb'] == 'Welcome' && $ret['version'] == '1.1.1') return($testhost);
            else show_debug("FAILED couchdb:".$testhost,'', __FILE__ ,__FUNCTION__, __LINE__);
        } else show_debug("FAILED fping:".$pingt." -t 50 ip=".$testhost,'', __FILE__ ,__FUNCTION__, __LINE__);
    }

Previously we were getting fping not found. So we installed that and after that we started getting  "(null): can't create socket (must run as root?) : Permission denied" error.

**Comment by urueedi** [comment]
if($testhost) {
//     $fping = exec("fping $testhost -t 50");
//     if($fping == $testhost.' is alive') {
$ret = json_decode(check_http('http://'.$testhost.':'.$dbport, 2),TRUE);
show_debug("Check couchdb:".$testhost.":".$dbport."/",'d', FILE ,FUNCTION, LINE);
if($ret['couchdb'] == 'Welcome' && $ret['version'] == '1.1.1') return($testhost);
else show_debug("FAILED couchdb:".$testhost,'', FILE ,FUNCTION, LINE);
//    } else show_debug("FAILED fping:".$pingt." -t 50 ip=".$testhost,'', FILE ,FUNCTION, LINE);
}

comment them out and try again (FILE ,FUNCTION, LINE is to see the exact line in code)

**Comment by smrdoshi** [comment]
Thank you very much. We can see the popup box with different phones now. 
We will test further.
