### ISSUE TITLE
yealink configuration webpage is blank

### ISSUE THREAD

**Issue by devangn** [urueedi/kazoo-provision#8]
[root@my-voice yealink]# pwd
/var/www/html/kazoo-provision/prov/yealink
[root@my-voice yealink]# ls
cfwd.php  dnd.php  firmware  index.html  lang  logout.php  pb.php  settings.php  startup.php

I have configured the yealink t21p for auto provisioning by changing the URL and also try binding the mac address of device with kazoo sip device

as per  #4

I should be able to see my-device-mac-address.cfg here, /var/www/html/kazoo-provision/prov/yealink/0123456789AB.cfg

What i am missing?
I have refer,
https://2600hz.atlassian.net/wiki/display/docs/Manual+Provisioning
https://2600hz.atlassian.net/wiki/pages/viewpage.action?pageId=27066376
for auto provision my yealink t21p

**Comment by urueedi** [comment]
Thats normal, to looup you have to use like this: URL/provisioner/prov/yealink/001577885533.cfg?mac=001577885533&qpass={urlpass}&model=yealinksip-t41g&firmware=Yealink SIP-T48G 35.80.0.70 00:15:77:88:33:55. It chacked many return strings of a phone.
